memo/accounts/urls.py
# myblog/accounts/urls.py

from django.urls import path

from . import views

# set the application namespace
# https://docs.djangoproject.com/en/2.0/intro/tutorial03/
app_name = 'accounts'

urlpatterns = [
    # ex: /accounts/signup/
    path('signup/', views.SignUpView.as_view(), name='signup'),
]

memo/app/urls.py
from django.urls import path
from . import views

app_name = 'app'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:memo_id>', views.detail, name='detail'),
    path('new_memo', views.new_memo, name='new_memo'),
    path('delete_memo/<int:memo_id>', views.delete_memo, name='delete_memo'),
    path('edit_memo/<int:memo_id>', views.edit_memo, name='edit_memo')
]

memo/memo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('accounts/', include('accounts.urls')), # [追加]
    path('accounts/',include('django.contrib.auth.urls'))
]

memo/accounts/models.py
from django.db import models

# Create your models here.

memo/app/models.py
from django.db import models

# Create your models here.
class Memo(models.Model):
    title = models.CharField(max_length=150)
    text = models.TextField(blank=True)
    created_datetime = models.DateTimeField(auto_now_add=True)
    updated_datetime = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

memo/app/forms.py
from django.forms import ModelForm
from .models import Memo
class MemoForm(ModelForm):
    class Meta:
        model=Memo
        fields=['title','text']

memo/accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic


class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'

memo/app/views.py
from django.shortcuts import render,redirect
from .models import Memo
from django.shortcuts import get_object_or_404
from .forms import MemoForm
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required

@login_required(login_url='/accounts/login/')
def index(request):
  memos = Memo.objects.all().order_by('-updated_datetime')
  return render(request, 'app/index.html', { 'memos': memos })


def detail(request, memo_id):
    #get_object_or_404 モデルの中のmemo_idにないidが
    #入力された時にエラーではなく404ページを表示する
  memo = get_object_or_404(Memo, id=memo_id)
  return render(request, 'app/detail.html', {'memo': memo})



#データベースに保存するときの典型的な形
def new_memo(request):
	if request.method == "POST":
		form = MemoForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('app:index')
	else:
		form = MemoForm
	return render(request, 'app/new_memo.html', {'form': form })



#method==GETのときは実行されない
@require_POST
def delete_memo(request, memo_id):
	memo = get_object_or_404(Memo, id=memo_id)
	memo.delete()
	return redirect('app:index')

#データベースの更新
def edit_memo(request, memo_id):
    memo = get_object_or_404(Memo, id=memo_id)
    if request.method == "POST":
        form = MemoForm(request.POST, instance=memo)
        if form.is_valid():
            form.save()
            return redirect('app:index')
    else:
        form = MemoForm(instance=memo)
    return render(request, 'app/edit_memo.html', {'form': form, 'memo':memo })

memo/accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
<h1>Sign up</h1>
<section class="common-form">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="submit">Sign up</button>
    </form>
</section>
{% endblock %}

memo/app/templates/app/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <title>MyBlog</title>
  <link rel="stylesheet" type="text/css" href="{% static 'app/css/style.css'%}">
</head>

<body>
  <h1>MyBlog</h1>

  <div class="container">
    {% block content %}{% endblock %}
  </div>
</body>
</html>

memo/app/templates/app/detail.html
{% extends 'app/base.html' %}
{% block content%}
  <div>
    <a href="{% url 'app:index' %}">ホームに戻る</a>
  </div>

  <h2>{{ memo.title }}</h2>
  <div>
    {{ memo.text | linebreaks | urlize }}
  </div>
  <button><a class="btn" href="{% url 'app:edit_memo' memo.pk %}">編集</a></button>
  <!--memo.pkの部分は<int:memo_id>で渡す値の指定-->
  <form method="post" action="{% url 'app:delete_memo' memo.pk %}">{% csrf_token %}
    <button class="btn" type="submit" onclick='return confirm("本当に削除しますか？");'>削除</button>
  </form>
{% endblock %}

memo/app/templates/app/edit_memo.html
{% extends 'app/base.html' %}
{% block content%}
  <div>
  <a href="{% url 'app:detail' memo.id %}">戻る</a>
  </div>

  <form action="{% url 'app:edit_memo' memo.id %}" method="POST">{% csrf_token %}
    <table>
      <tr>
        <th>タイトル</th>
        <td>{{ form.title }}</td>
      </tr>
      <tr>
        <th>テキスト</th>
        <td>{{ form.text }}</td>
      </tr>
    </table>
    <button class="btn" type="submit">保存</button>
  </form>
{% endblock %}

memo/app/templates/app/index.html
{% extends 'app/base.html' %}
{% block content%}
  <a class="btn" href="{% url 'app:new_memo' %}">新規メモ作成</a>

  {% for memo in memos %}
  <a href="{% url 'app:detail' memo.id %}" class="memo-title">
    <div>
      {{ memo }}
      <span class="updated_datetime">{{ memo.updated_datetime }}</span>
    </div>
  </a>
{% endfor %}
{% endblock %}

memo/app/templates/app/new_memo.html
{% extends 'app/base.html' %}
{% block content%}
  <div>
    <a href="{% url 'app:index' %}">ホームに戻る</a>
  </div>
  <!--{% csrf_token %}はセキュリティー対策
  ないとエラーがでる-->
  <form action="{% url 'app:new_memo' %}" method="POST">{% csrf_token %}
    <!-- .as_p <p>タグで囲む -->
    {{ form.as_p }}
    <button type="submit" class="btn">保存</button>
  </form>
{% endblock %}

memo/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <title>{% if request.path != '/' %}{% block title %}{% endblock %} | {% endif %}Blog App with Auth | Django2 Tutorial</title>
    
<body>
<div class="container">
    <header>
        <p class="site-name">Blog App</p>
        <nav>
            <ul>
                {% if user.is_authenticated %}
                <li><a href="{% url 'logout' %}" class="logout">Logout</a></li>
                {% else %}
                <li><a href="{% url 'accounts:signup' %}" class="signup">Sign up</a></li>
                <li><a href="{% url 'login' %}" class="login">Login</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>
    <div class="content">
        {% block content %}{% endblock %}
    </div>
</div>
</body>